### ISSUE TITLE
Drop esdoc

### ISSUE THREAD

**Issue by wbt** [trufflesuite/reselect-tree#10]
This project has a [dependency](https://github.com/trufflesuite/reselect-tree/blob/e3e3aad5e5145f2b4b75b6540ed51ab85c008b14/package.json#L32) on [es-doc](https://github.com/esdoc/esdoc) which hasn't been updated in > 4 years and has at least one transient [Critical-level vulnerability](https://github.com/advisories/GHSA-xvch-5gv4-984h) due to [tightly pinning its version of minimist](https://github.com/esdoc/esdoc/blob/38ad523936d425278cc037c9c0e11338faa2709b/package.json#L35).  A [PR](https://github.com/esdoc/esdoc/pull/575) to update that has been open 23 days without review.  That Critical-level audit failure is affecting this project and any that use it, including [@truffle/debugger@10.0.8](https://github.com/trufflesuite/truffle/blob/1fb5559aed29a3e177538d8118f06cf848c529ab/packages/debugger/package.json#L35) and truffle@5.5.12. 

Dropping es-doc as a dependency seems like the best option here.

**Comment by gnidan** [comment]
Good call! We should be able to get this removed in time for this week's Truffle release. Thanks for reporting this!

**Comment by haltman-at** [comment]
OK, should be fixed in 1.3.6.
